import csv
import pickle
from pathlib import Path

import numpy as np

from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import roc_auc_score


DATA = Path(
    "routing/benchmarks/results/"
    "wearvqa_e2b_50_graded.csv"
)

MODEL_OUT = Path(
    "routing/routellm_v2/proxy_router.pkl"
)

SCORES_OUT = Path(
    "routing/routellm_v2/results/"
    "proxy_router_loo_scores.csv"
)


# ============================================================
# LOAD MANUALLY GRADED SMALL-MODEL RESULTS
# ============================================================

with open(DATA, newline="", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

rows = [
    r for r in rows
    if r["manual_correct"] in {"0", "1"}
]

questions = [
    r["question"]
    for r in rows
]

# RouteLLM-style proxy target:
#
# y = 1:
#     SMALL failed -> candidate for LARGE
#
# y = 0:
#     SMALL succeeded -> SMALL sufficient
#
# Later, when LARGE is available, replace this target with:
#
# y = 1:
#     LARGE provides useful gain / rescue over SMALL
#
labels = np.array([
    1 if r["manual_correct"] == "0" else 0
    for r in rows
])


def make_router():
    """
    Lightweight request-level routing model.

    Word features:
        useful for semantic task clues

    Character features:
        useful for small datasets and wording variation

    Classifier:
        Logistic Regression, lightweight enough for edge routing
    """

    features = FeatureUnion([
        (
            "word",
            TfidfVectorizer(
                analyzer="word",
                ngram_range=(1, 2),
                min_df=1,
                sublinear_tf=True,
            ),
        ),
        (
            "char",
            TfidfVectorizer(
                analyzer="char_wb",
                ngram_range=(3, 5),
                min_df=2,
                sublinear_tf=True,
                max_features=5000,
            ),
        ),
    ])

    return Pipeline([
        ("features", features),
        (
            "router",
            LogisticRegression(
                C=1.0,
                max_iter=3000,
                class_weight="balanced",
                random_state=40,
            ),
        ),
    ])


print()
print("=" * 78)
print("ROUTELLM-INSPIRED WHICH V2")
print("=" * 78)

print("Judgeable samples :", len(rows))
print("SMALL failures    :", int(labels.sum()))
print("SMALL successes   :", int((1 - labels).sum()))


# ============================================================
# LEAVE-ONE-OUT
#
# Every score is generated by a model that did not train
# on that particular sample.
# ============================================================

loo = LeaveOneOut()

scores = np.zeros(
    len(rows),
    dtype=float,
)


for fold, (train_idx, test_idx) in enumerate(
    loo.split(questions),
    start=1,
):

    train_q = [
        questions[i]
        for i in train_idx
    ]

    train_y = labels[
        train_idx
    ]

    test_q = [
        questions[i]
        for i in test_idx
    ]

    model = make_router()

    model.fit(
        train_q,
        train_y,
    )

    score = model.predict_proba(
        test_q
    )[0, 1]

    scores[
        test_idx[0]
    ] = score


auc = roc_auc_score(
    labels,
    scores,
)


print()
print(
    "LOO ROC-AUC       :",
    f"{auc:.3f}",
)


# ============================================================
# SAVE OUT-OF-SAMPLE SCORES
# ============================================================

SCORES_OUT.parent.mkdir(
    parents=True,
    exist_ok=True,
)


with open(
    SCORES_OUT,
    "w",
    newline="",
    encoding="utf-8",
) as f:

    writer = csv.DictWriter(
        f,
        fieldnames=[
            "sample_id",
            "category",
            "question",
            "manual_correct",
            "small_failed",
            "router_score",
        ],
    )

    writer.writeheader()

    for r, label, score in zip(
        rows,
        labels,
        scores,
    ):

        writer.writerow({
            "sample_id": r["sample_id"],
            "category": r["category"],
            "question": r["question"],
            "manual_correct": r["manual_correct"],
            "small_failed": int(label),
            "router_score": f"{score:.6f}",
        })


# ============================================================
# TRAIN DEPLOYABLE MODEL
# ============================================================

final_router = make_router()

final_router.fit(
    questions,
    labels,
)


with open(
    MODEL_OUT,
    "wb",
) as f:

    pickle.dump(
        final_router,
        f,
    )


print(
    "Saved LOO scores :",
    SCORES_OUT,
)

print(
    "Saved model      :",
    MODEL_OUT,
)

print()
